import { Contacts } from 'expo';

export default {
  en: {
    [Contacts.Fields.ID]: 'ID',
    [Contacts.Fields.ContactType]: 'Contact Type',
    [Contacts.Fields.Name]: 'Name',
    [Contacts.Fields.FirstName]: 'First Name',
    [Contacts.Fields.MiddleName]: 'Middle Name',
    [Contacts.Fields.LastName]: 'Last Name',
    [Contacts.Fields.MaidenName]: 'Maiden Name',
    [Contacts.Fields.NamePrefix]: 'Prefix',
    [Contacts.Fields.NameSuffix]: 'Suffix',
    [Contacts.Fields.Nickname]: 'Nickname',
    [Contacts.Fields.PhoneticFirstName]: 'Phonetic First Name',
    [Contacts.Fields.PhoneticMiddleName]: 'Phonetic Middle Name',
    [Contacts.Fields.PhoneticLastName]: 'Phonetic Last Name',
    [Contacts.Fields.Birthday]: 'Birthday',
    [Contacts.Fields.NonGregorianBirthday]: 'Non-Gregorian Birthday',
    [Contacts.Fields.Emails]: 'Email Addresses',
    [Contacts.Fields.PhoneNumbers]: 'Phone Numbers',
    [Contacts.Fields.Addresses]: 'Addresses',
    [Contacts.Fields.SocialProfiles]: 'Social Profiles',
    [Contacts.Fields.InstantMessageAddresses]: 'Instant Message Addresses',
    [Contacts.Fields.UrlAddresses]: 'URL Addresses',
    [Contacts.Fields.Company]: 'Company',
    [Contacts.Fields.JobTitle]: 'Job Title',
    [Contacts.Fields.Department]: 'Department',
    [Contacts.Fields.ImageAvailable]: 'Image Available',
    [Contacts.Fields.Image]: 'Image',
    [Contacts.Fields.RawImage]: 'Raw Image',
    [Contacts.Fields.Note]: 'Note',
    [Contacts.Fields.Dates]: 'Dates',
    [Contacts.Fields.Relationships]: 'Relationships',
  },
};
